### ISSUE TITLE
<Navigation> is missing

### ISSUE THREAD

**Issue by mrpsiho** [diegohaz/reas#101]
Hi!

First, thanks for such a cool lib!
Unfortunately, I have got this: `'reas' does not contain an export named 'Navigation'.` I am using `reas` NPM package (0.10.2), just checked it - it really does not have such component :(

**Comment by Thomazella** [comment]
Hi mrpsiho! Thanks for reporting it. We'll have it fixed soon.

**Comment by diegohaz** [comment]
Hey, @mrpsiho. I just released a new version ([`v0.10.3`](https://github.com/diegohaz/reas/releases/tag/v0.10.3)). Please, run `npm update reas` or `yarn upgrade reas`.

**Comment by mrpsiho** [comment]
Awesome! Thanks again for the great tool! 🥇
