### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/reas#27]
References:
- http://nikgraf.github.io/belle/#/component/card?_k=zc4tyc
- http://jxnblk.com/rebass/components/Card
- https://react.semantic-ui.com/views/card
- http://www.material-ui.com/#/components/card

**Comment by jyash97** [comment]
Can i take this it it's competed?

**Comment by diegohaz** [comment]
Go ahead, @jyash97. Tell me if you need any help.
