### ISSUE TITLE
Image component

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/reas#28]
References:
- https://react.semantic-ui.com/elements/image
- http://jxnblk.com/rebass/components/Image

**Comment by klimcode** [comment]
Hi. I wanna try to do it. Do you have an instruction which can help me to start?

**Comment by diegohaz** [comment]
Sure, @klimcode:

1. Fork, clone the repository in your local machine and install dependencies (`yarn` or `npm install`);
2. Run `yarn docs` or `npm run docs` and open http://localhost:6060 in your browser;
3. Duplicate any simple component inside `src/components` (e.g. `Block`) naming it `Image` ([generact](https://github.com/diegohaz/generact) can help you with that);
4. Update `Image.js` to create the component and `Image.md` to update docs (and to see if everything is working);
5. Update `src/components/index.js` to add `Image.js` to exports.

**Comment by diegohaz** [comment]
Closed in #84
